openapi: 3.0.4
info:
  title: Online Shop - API
  description: This is a sample API
  contact:
    email: 22028061@vnu.edu.vn
  license:
    name: MIT
  version: 1.0.0
servers:
- url: /
tags:
- name: product
paths:
  /products:
    get:
      tags:
      - product
      summary: Get a list of products
      description: Return a list of products
      operationId: get_product
      parameters:
      - name: page
        in: query
        required: false
        style: form
        explode: true
        schema:
          minimum: 1
          type: integer
          format: int32
          default: 1
      - name: per_page
        in: query
        required: false
        style: form
        explode: true
        schema:
          maximum: 50
          minimum: 1
          type: integer
          format: int32
          default: 10
      responses:
        "200":
          description: Successful oepration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_200"
      x-openapi-router-controller: swagger_server.controllers.product_controller
    post:
      tags:
      - product
      summary: Add a new product
      description: Create a new product in the database
      operationId: create_product
      requestBody:
        description: Add a new product in the store
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: Invalid input
        "422":
          description: Validation exception
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
      - api_key: []
      x-openapi-router-controller: swagger_server.controllers.product_controller
  /product/{product_id}:
    get:
      tags:
      - product
      summary: Get a product by id
      description: Request a product by id
      operationId: get_product_by_id
      parameters:
      - name: product_id
        in: path
        description: The product's id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          default: 123
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_200_1"
        "400":
          description: Invalid input
        "404":
          description: Resource not found
        "422":
          description: Validation exception
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      x-openapi-router-controller: swagger_server.controllers.product_controller
    put:
      tags:
      - product
      summary: Update a product values by id
      description: "Update a product's quantity, name"
      operationId: product_product_id_put
      parameters:
      - name: product_id
        in: path
        description: The product's id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          default: 123
      requestBody:
        description: Update a product's attribute by product_id
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Successful update
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
      security:
      - api_key: []
      x-openapi-router-controller: swagger_server.controllers.product_controller
    delete:
      tags:
      - product
      summary: Delete a product by id
      description: Remove a product permanently
      operationId: delete_product_by_id
      parameters:
      - name: product_id
        in: path
        description: The product's id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Product deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_200_2"
      security:
      - api_key: []
      x-openapi-router-controller: swagger_server.controllers.product_controller
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 69
        productName:
          type: string
          example: Dell Laptop
        productCode:
          type: integer
          format: int64
          example: 66771508
        quantity:
          type: integer
          format: int32
          example: 12
      example:
        productCode: 66771508
        quantity: 12
        id: 69
        productName: Dell Laptop
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    Pagination:
      type: object
      properties:
        page:
          type: integer
          format: int32
          example: 1
        per_page:
          type: integer
          format: int32
          example: 20
        total_pages:
          type: integer
          format: int32
          example: 10
        total_items:
          type: integer
          format: int32
          example: 200
      example:
        per_page: 20
        page: 1
        total_pages: 10
        total_items: 200
    Link:
      type: object
      properties:
        href:
          type: string
          example: api/product?page=2
        rel:
          type: string
          example: next
        method:
          type: string
          example: GET
      example:
        method: GET
        rel: next
        href: api/product?page=2
    HATEOAS:
      type: object
      properties:
        _links:
          type: array
          items:
            $ref: "#/components/schemas/Link"
      example:
        _links:
        - method: GET
          rel: next
          href: api/product?page=2
        - method: GET
          rel: next
          href: api/product?page=2
    inline_response_200:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: "#/components/schemas/Product"
        pagination:
          $ref: "#/components/schemas/Pagination"
        _links:
          $ref: "#/components/schemas/HATEOAS"
      example:
        pagination:
          per_page: 20
          page: 1
          total_pages: 10
          total_items: 200
        _links:
          _links:
          - method: GET
            rel: next
            href: api/product?page=2
          - method: GET
            rel: next
            href: api/product?page=2
        products:
        - productCode: 66771508
          quantity: 12
          id: 69
          productName: Dell Laptop
        - productCode: 66771508
          quantity: 12
          id: 69
          productName: Dell Laptop
    inline_response_200_1:
      type: object
      properties:
        product:
          $ref: "#/components/schemas/Product"
        _links:
          $ref: "#/components/schemas/HATEOAS"
      example:
        product:
          productCode: 66771508
          quantity: 12
          id: 69
          productName: Dell Laptop
        _links:
          _links:
          - method: GET
            rel: next
            href: api/product?page=2
          - method: GET
            rel: next
            href: api/product?page=2
    inline_response_200_2:
      type: object
      properties:
        message:
          type: string
          example: Product deleted successfully
      example:
        message: Product deleted successfully
  parameters:
    PageParam:
      name: page
      in: query
      required: false
      style: form
      explode: true
      schema:
        minimum: 1
        type: integer
        format: int32
        default: 1
    PerPageParam:
      name: per_page
      in: query
      required: false
      style: form
      explode: true
      schema:
        maximum: 50
        minimum: 1
        type: integer
        format: int32
        default: 10
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.check_api_key

